apiVersion: apps/v1
kind: Deployment
metadata:
  name: infoasst-reranker
  namespace: infoasst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infoasst-reranker
  template:
    metadata:
      labels:
        app: infoasst-reranker
    spec:
      containers:
      - name: infoasst-reranker
        image: {{ .Values.images.reranker.repository }}:{{ .Values.images.reranker.label }}
        env:
          - name: ENABLE_CUDA
            value: "{{ .Values.reranker.env.enablecuda }}"
        resources:
          limits:
            memory: "12G"
            cpu: "500m"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: infoasst-reranker
  namespace: infoasst
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: infoasst-reranker
--- 


