apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infoasst-weaviate
  namespace: infoasst
spec:
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce