# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/python:4-python3.7-appservice
FROM mcr.microsoft.com/azure-functions/python:4-python3.11
 
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true
 
COPY ./functions /home/site/wwwroot
 
RUN cd /home/site/wwwroot && \
  pip install --upgrade pip && \
  pip install -r requirements.txt && \
  cd --