## TODO - we need to rely on the output from the build process for this to work.

FROM python:3.10

WORKDIR /enrichment

COPY enrichment/ /enrichment

RUN pip3 install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

EXPOSE 5000

CMD gunicorn -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 app:app
