## TODO - we need to rely on the output from the build process for this to work.

FROM python:3.10

WORKDIR /webapp

COPY webapp/ /webapp

RUN pip3 install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

EXPOSE 80

CMD gunicorn --timeout 300 --bind 0.0.0.0:80 app:app --threads 100
