
FROM python:3.10

WORKDIR /webapp

COPY webapp/ /webapp

RUN pip3 install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app:app"]
